# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a093d97c197c38a7f8bc63e69cc953f25307c81b1e999fc5581abfb5d472a0d52caf3d3e8b7f563d8dfd03e18c29a9329e726f57c35352128286ca5fb1505012

test:
  secret_key_base: 7b314f89c9e30db82122b93ccd5553b443967776bdf1eb7105e8b362c800e983404a1f73853a7cbc6e72e2f1de0a6ae98e4f4702bdc72b1d8f521c6f65c5eeac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
